"""Curated academic-register synonym bank.

In academic style the humanizer substitutes *only* through this bank instead
of the broad (casual-leaning) tone dictionary, so every swap is a genuine
scholarly-register alternative and stays grammatically substitutable (entries
are inflection-matched: ``show`` / ``shows`` / ``showed`` / ``shown`` are
separate keys).  Words absent from the bank are left untouched -- which is
exactly what a careful human editor of a paper does.

Pure data plus a tiny lookup; no imports from the rest of the package so it is
safe to import anywhere.
"""

from __future__ import annotations

from typing import Dict, List

# --------------------------------------------------------------------------- #
# Verbs (inflection-matched groups).
# --------------------------------------------------------------------------- #
_VERBS: Dict[str, List[str]] = {
    "use": ["employ", "apply", "utilize", "adopt"],
    "uses": ["employs", "applies", "utilizes", "adopts"],
    "used": ["employed", "applied", "utilized", "adopted"],
    "using": ["employing", "applying", "utilizing", "adopting"],
    "show": ["demonstrate", "indicate", "reveal", "report"],
    "shows": ["demonstrates", "indicates", "reveals", "reports"],
    "showed": ["demonstrated", "indicated", "revealed", "reported"],
    "shown": ["demonstrated", "indicated", "reported"],
    "improve": ["enhance", "refine", "strengthen"],
    "improves": ["enhances", "refines", "strengthens"],
    "improved": ["enhanced", "refined", "strengthened"],
    "improving": ["enhancing", "refining", "strengthening"],
    "support": ["corroborate", "reinforce", "substantiate", "underpin"],
    "supports": ["corroborates", "reinforces", "substantiates", "underpins"],
    "supported": ["corroborated", "reinforced", "substantiated"],
    "address": ["tackle", "mitigate", "handle"],
    "addresses": ["tackles", "mitigates", "handles"],
    "addressed": ["tackled", "mitigated", "handled"],
    "propose": ["put forward", "introduce", "present"],
    "proposes": ["puts forward", "introduces", "presents"],
    "proposed": ["put forward", "introduced", "presented"],
    "investigate": ["examine", "explore", "study"],
    "investigated": ["examined", "explored", "studied"],
    "investigates": ["examines", "explores", "studies"],
    "develop": ["devise", "build", "construct"],
    "developed": ["devised", "built", "constructed"],
    "develops": ["devises", "builds", "constructs"],
    "implement": ["deploy", "realize", "apply"],
    "implemented": ["deployed", "realized", "applied"],
    "implements": ["deploys", "realizes", "applies"],
    "evaluate": ["assess", "appraise", "gauge"],
    "evaluated": ["assessed", "appraised", "gauged"],
    "evaluates": ["assesses", "appraises", "gauges"],
    "analyze": ["examine", "assess", "characterize"],
    "analyzed": ["examined", "assessed", "characterized"],
    "analyzes": ["examines", "assesses", "characterizes"],
    "achieve": ["attain", "obtain", "reach"],
    "achieved": ["attained", "obtained", "reached"],
    "achieves": ["attains", "obtains", "reaches"],
    "enable": ["allow", "permit", "facilitate"],
    "enables": ["allows", "permits", "facilitates"],
    "enabled": ["allowed", "permitted", "facilitated"],
    "provide": ["offer", "yield", "afford", "deliver"],
    "provides": ["offers", "yields", "affords", "delivers"],
    "provided": ["offered", "yielded", "afforded"],
    "require": ["necessitate", "demand", "call for"],
    "requires": ["necessitates", "demands", "calls for"],
    "required": ["necessitated", "demanded"],
    "affect": ["influence", "impact", "alter"],
    "affects": ["influences", "impacts", "alters"],
    "affected": ["influenced", "impacted", "altered"],
    "identify": ["detect", "recognize", "distinguish"],
    "identified": ["detected", "recognized", "distinguished"],
    "identifies": ["detects", "recognizes", "distinguishes"],
    "obtain": ["acquire", "derive", "secure"],
    "obtained": ["acquired", "derived", "secured"],
    "observe": ["note", "record", "report"],
    "observed": ["noted", "recorded", "reported"],
    "examine": ["investigate", "assess", "inspect"],
    "examined": ["investigated", "assessed", "inspected"],
    "establish": ["determine", "ascertain", "confirm"],
    "established": ["determined", "ascertained", "confirmed"],
    "present": ["report", "describe", "outline"],
    "presented": ["reported", "described", "outlined"],
    "describe": ["characterize", "outline", "detail"],
    "described": ["characterized", "outlined", "detailed"],
    "focus": ["concentrate", "center"],
    "focuses": ["concentrates", "centers"],
    "focused": ["concentrated", "centered"],
    "indicate": ["suggest", "imply", "signal"],
    "indicates": ["suggests", "implies", "signals"],
    "indicated": ["suggested", "implied", "signaled"],
    "suggest": ["indicate", "imply", "point to"],
    "suggests": ["indicates", "implies", "points to"],
    "suggested": ["indicated", "implied"],
    "integrate": ["combine", "incorporate", "couple"],
    "integrated": ["combined", "incorporated", "coupled"],
    "monitor": ["track", "observe", "survey"],
    "monitored": ["tracked", "observed", "surveyed"],
    "monitoring": ["tracking", "observation", "surveillance"],
    "detect": ["identify", "recognize", "sense"],
    "detected": ["identified", "recognized", "sensed"],
    "verify": ["confirm", "validate", "corroborate"],
    "verified": ["confirmed", "validated", "corroborated"],
    "ensure": ["guarantee", "secure", "safeguard"],
    "consider": ["examine", "regard", "treat"],
    "considered": ["examined", "regarded", "treated"],
    "determine": ["establish", "ascertain", "identify"],
    "determined": ["established", "ascertained", "identified"],
    "perform": ["carry out", "conduct", "execute"],
    "performed": ["carried out", "conducted", "executed"],
    "conduct": ["carry out", "perform", "undertake"],
    "conducted": ["carried out", "performed", "undertaken"],
    "limit": ["constrain", "restrict", "bound"],
    "limits": ["constrains", "restricts", "bounds"],
    "limited": ["constrained", "restricted", "bounded"],
    "evolve": ["develop", "advance", "progress"],
    "highlight": ["underscore", "emphasize", "foreground"],
    "highlights": ["underscores", "emphasizes"],
    "highlighted": ["underscored", "emphasized"],
    # --- domain verbs: CV / ML / edge / sensing -----------------------------
    "leverage": ["exploit", "harness", "draw on"],
    "leverages": ["exploits", "harnesses", "draws on"],
    "leveraged": ["exploited", "harnessed", "drew on"],
    "utilize": ["employ", "use", "apply"],
    "utilizes": ["employs", "uses", "applies"],
    "utilized": ["employed", "used", "applied"],
    "facilitate": ["enable", "support", "ease"],
    "facilitates": ["enables", "supports", "eases"],
    "facilitated": ["enabled", "supported", "eased"],
    "demonstrate": ["show", "establish", "confirm"],
    "demonstrates": ["shows", "establishes", "confirms"],
    "demonstrated": ["shown", "established", "confirmed"],
    "validate": ["verify", "confirm", "corroborate"],
    "validated": ["verified", "confirmed", "corroborated"],
    "optimize": ["refine", "tune", "improve"],
    "optimized": ["refined", "tuned", "improved"],
    "mitigate": ["reduce", "alleviate", "lessen"],
    "mitigated": ["reduced", "alleviated", "lessened"],
    "incorporate": ["integrate", "include", "embed"],
    "incorporated": ["integrated", "included", "embedded"],
    "deploy": ["implement", "install", "operationalize"],
    "deployed": ["implemented", "installed", "operationalized"],
    "classify": ["categorize", "label", "discriminate"],
    "classified": ["categorized", "labeled", "discriminated"],
    "segment": ["partition", "delineate", "isolate"],
    "segmented": ["partitioned", "delineated", "isolated"],
    "annotate": ["label", "tag", "mark"],
    "annotated": ["labeled", "tagged", "marked"],
    "train": ["fit", "optimize"],
    "trained": ["fitted", "optimized"],
    "infer": ["predict", "estimate", "deduce"],
    "inferred": ["predicted", "estimated", "deduced"],
    "predict": ["estimate", "forecast", "anticipate"],
    "predicted": ["estimated", "forecast", "anticipated"],
    "estimate": ["approximate", "compute", "infer"],
    "estimated": ["approximated", "computed", "inferred"],
    "localize": ["locate", "position", "pinpoint"],
    "localized": ["located", "positioned", "pinpointed"],
    "calibrate": ["tune", "adjust", "align"],
    "calibrated": ["tuned", "adjusted", "aligned"],
    "benchmark": ["evaluate", "compare", "assess"],
    "benchmarked": ["evaluated", "compared", "assessed"],
    "outperform": ["surpass", "exceed", "outstrip"],
    "outperforms": ["surpasses", "exceeds", "outstrips"],
    "outperformed": ["surpassed", "exceeded", "outstripped"],
    "process": ["handle", "compute", "analyze"],
    "processed": ["handled", "computed", "analyzed"],
    "extract": ["derive", "obtain", "isolate"],
    "extracted": ["derived", "obtained", "isolated"],
    "capture": ["record", "acquire", "register"],
    "captured": ["recorded", "acquired", "registered"],
    "recognize": ["identify", "detect", "discern"],
    "recognized": ["identified", "detected", "discerned"],
    "track": ["follow", "trace", "monitor"],
    "tracked": ["followed", "traced", "monitored"],
    "reduce": ["lower", "diminish", "curtail"],
    "reduced": ["lowered", "diminished", "curtailed"],
    "increase": ["raise", "boost", "augment"],
    "increased": ["raised", "boosted", "augmented"],
    "assume": ["presume", "posit", "hypothesize"],
    "assumed": ["presumed", "posited", "hypothesized"],
    "test": ["evaluate", "examine", "assess"],
    "tested": ["evaluated", "examined", "assessed"],
    "compare": ["contrast", "juxtapose", "benchmark"],
    "compared": ["contrasted", "juxtaposed", "benchmarked"],
    "combine": ["integrate", "merge", "fuse"],
    "combined": ["integrated", "merged", "fused"],
    "apply": ["employ", "use", "adopt"],
    "applied": ["employed", "used", "adopted"],
    "applies": ["employs", "uses", "adopts"],}

# --------------------------------------------------------------------------- #
# Nouns.
# --------------------------------------------------------------------------- #
_NOUNS: Dict[str, List[str]] = {
    "study": ["investigation", "analysis", "work"],
    "studies": ["investigations", "analyses", "works"],
    "research": ["investigation", "scholarship", "inquiry"],
    "finding": ["result", "observation", "outcome"],
    "findings": ["results", "observations", "outcomes"],
    "result": ["outcome", "finding"],
    "results": ["outcomes", "findings"],
    "approach": ["method", "technique", "strategy"],
    "approaches": ["methods", "techniques", "strategies"],
    "method": ["approach", "technique", "procedure"],
    "methods": ["approaches", "techniques", "procedures"],
    "technique": ["method", "approach", "procedure"],
    "techniques": ["methods", "approaches", "procedures"],
    "system": ["framework", "architecture", "platform"],
    "systems": ["frameworks", "architectures", "platforms"],
    "framework": ["architecture", "scheme", "model"],
    "performance": ["effectiveness", "accuracy"],
    "accuracy": ["precision", "correctness"],
    "limitation": ["constraint", "shortcoming", "drawback"],
    "limitations": ["constraints", "shortcomings", "drawbacks"],
    "challenge": ["difficulty", "obstacle"],
    "challenges": ["difficulties", "obstacles"],
    "concern": ["issue", "consideration"],
    "concerns": ["issues", "considerations"],
    "issue": ["problem", "concern", "difficulty"],
    "issues": ["problems", "concerns", "difficulties"],
    "problem": ["issue", "difficulty", "limitation"],
    "advantage": ["benefit", "strength"],
    "advantages": ["benefits", "strengths"],
    "benefit": ["advantage", "gain"],
    "ability": ["capability", "capacity"],
    "capability": ["ability", "capacity"],
    "environment": ["setting", "context"],
    "scenario": ["setting", "case", "context"],
    "scenarios": ["settings", "cases", "contexts"],
    "context": ["setting", "domain"],
    # --- domain nouns: CV / ML / edge / sensing -----------------------------
    "dataset": ["data set", "corpus", "collection"],
    "datasets": ["data sets", "corpora", "collections"],
    "model": ["network", "architecture"],
    "models": ["networks", "architectures"],
    "algorithm": ["procedure", "scheme", "routine"],
    "algorithms": ["procedures", "schemes", "routines"],
    "architecture": ["design", "structure", "topology"],
    "module": ["component", "unit", "block"],
    "modules": ["components", "units", "blocks"],
    "pipeline": ["workflow", "processing chain"],
    "inference": ["prediction", "estimation"],
    "throughput": ["processing rate", "data rate"],
    "latency": ["delay", "response time"],
    "robustness": ["resilience", "stability"],
    "scalability": ["extensibility"],
    "deployment": ["implementation", "rollout"],
    "sensor": ["detector", "transducer"],
    "sensors": ["detectors", "transducers"],
    "node": ["device", "unit", "endpoint"],
    "nodes": ["devices", "units", "endpoints"],
    "feature": ["attribute", "characteristic", "descriptor"],
    "features": ["attributes", "characteristics", "descriptors"],
    "parameter": ["hyperparameter", "coefficient", "setting"],
    "parameters": ["hyperparameters", "coefficients", "settings"],
    "metric": ["measure", "indicator", "criterion"],
    "metrics": ["measures", "indicators", "criteria"],
    "baseline": ["reference", "benchmark"],
    "occlusion": ["obstruction", "blockage"],
    "illumination": ["lighting", "light conditions"],
    "annotation": ["labeling", "tagging"],
    "classifier": ["detector", "model"],
    "detector": ["model", "classifier"],
    "object": ["item", "target", "entity"],
    "objects": ["items", "targets", "entities"],
    "item": ["object", "article", "entity"],
    "items": ["objects", "articles", "entities"],
    "device": ["unit", "hardware", "module"],
    "devices": ["units", "hardware", "modules"],
    "data": ["information", "measurements"],
    "noise": ["interference", "perturbation"],
    "estimation": ["prediction", "inference"],
    "detection": ["identification", "recognition"],
    "recognition": ["identification", "detection"],
    "verification": ["validation", "confirmation"],
    "tracking": ["monitoring", "tracing"],
    "implementation": ["deployment", "realization"],
    "evaluation": ["assessment", "appraisal"],
    "improvement": ["enhancement", "refinement", "gain"],
    "improvements": ["enhancements", "refinements", "gains"],
}

# --------------------------------------------------------------------------- #
# Adjectives / adverbs.
# --------------------------------------------------------------------------- #
_ADJ: Dict[str, List[str]] = {
    "important": ["significant", "notable", "considerable"],
    "significant": ["substantial", "notable", "considerable"],
    "key": ["central", "principal", "primary"],
    "crucial": ["essential", "critical", "vital"],
    "essential": ["fundamental", "critical", "necessary"],
    "effective": ["robust", "reliable", "successful"],
    "efficient": ["economical", "streamlined"],
    "accurate": ["precise", "reliable", "exact"],
    "reliable": ["dependable", "consistent", "robust"],
    "robust": ["resilient", "stable", "reliable"],
    "complex": ["intricate", "complicated", "elaborate"],
    "difficult": ["challenging", "demanding", "non-trivial"],
    "simple": ["straightforward", "elementary"],
    "novel": ["new", "original"],
    "recent": ["current", "contemporary"],
    "various": ["several", "diverse", "differing"],
    "numerous": ["many", "multiple", "several"],
    "large": ["substantial", "considerable", "extensive"],
    "small": ["limited", "modest", "minor"],
    "fast": ["rapid", "swift", "efficient"],
    "slow": ["gradual", "protracted"],
    "limited": ["constrained", "restricted", "narrow"],
    "widely": ["extensively", "broadly", "commonly"],
    "often": ["frequently", "commonly", "typically"],
    "clearly": ["evidently", "demonstrably"],
    # --- domain adjectives --------------------------------------------------
    "scalable": ["extensible", "expandable"],
    "lightweight": ["low-overhead", "compact"],
    "embedded": ["on-device", "integrated"],
    "computational": ["processing", "numerical"],
    "empirical": ["experimental", "observed"],
    "quantitative": ["numerical", "measured"],
    "qualitative": ["descriptive", "non-numerical"],
    "comparative": ["relative", "contrastive"],
    "preliminary": ["initial", "early-stage", "tentative"],
    "promising": ["encouraging", "favorable"],
    "feasible": ["viable", "practical", "achievable"],
    "viable": ["feasible", "workable", "practical"],
    "optimal": ["best-performing", "ideal"],
    "computationally": ["numerically"],
    "real-time": ["online", "live"],
    "indoor": ["interior", "in-building"],
    "automated": ["automatic", "autonomous"],
}

# --------------------------------------------------------------------------- #
# Multi-word academic phrasings.
# --------------------------------------------------------------------------- #
_PHRASES: Dict[str, List[str]] = {
    "a lot of": ["a substantial amount of", "considerable", "extensive"],
    "lots of": ["numerous", "considerable"],
    "make use of": ["employ", "utilize", "draw on"],
    "based on": ["grounded in", "derived from", "informed by"],
    "show that": ["demonstrate that", "indicate that", "reveal that"],
    "showed that": ["demonstrated that", "indicated that", "revealed that"],
    "found that": ["determined that", "observed that", "reported that"],
    "a number of": ["several", "various", "multiple"],
    "play a role": ["contribute", "be a factor"],
    "deal with": ["address", "handle", "treat"],
    "look at": ["examine", "consider", "investigate"],
    "point out": ["note", "observe", "indicate"],
    "carried out": ["conducted", "performed", "undertaken"],
    "real-time": ["real-time", "online", "live"],
}

ACADEMIC_LEXICON: Dict[str, List[str]] = {}
for _grp in (_VERBS, _NOUNS, _ADJ, _PHRASES):
    ACADEMIC_LEXICON.update(_grp)


def academic_options(word: str) -> List[str]:
    """Return curated academic-register alternatives for ``word`` (lower-cased),
    or an empty list when the word should be left untouched."""
    return list(ACADEMIC_LEXICON.get((word or "").strip().lower(), []))


def merged_lexicon(project: Dict[str, List[str]]) -> Dict[str, List[str]]:
    """Base academic bank with a per-project synonym map layered on top.

    Project options are listed first (preferred) and merged with any base
    options for the same head-word, de-duplicated.  New project head-words are
    added.  Keys are lower-cased; empty / malformed entries are ignored.
    """
    if not project:
        return dict(ACADEMIC_LEXICON)
    out: Dict[str, List[str]] = {k: list(v) for k, v in ACADEMIC_LEXICON.items()}
    for raw_k, raw_v in project.items():
        key = str(raw_k).strip().lower()
        if not key or not isinstance(raw_v, (list, tuple)):
            continue
        opts = [str(x).strip() for x in raw_v if str(x).strip()]
        if not opts:
            continue
        merged = list(dict.fromkeys(opts + out.get(key, [])))
        out[key] = merged
    return out
